#!/bin/bash

pkgname=nagios-plugins-2.2.1

echo NAGIOSPLUGINS

# Delete the old directory
rm -rf $pkgname

# Extract archive
tar xzf $pkgname.tar.gz

(
	cd $pkgname
	time ./configure --libexecdir=/usr/local/nagios/libexec
	time make clean
	time make
	time make install
)

